timeout: 3
backdrop: ff0b1220

term_background: ff0b1220
term_foreground: ffffff
term_wallpaper: boot():/res/BG.BMP
wallpaper: boot():/res/BG.BMP

# Пункт 1: Стандартный тихий запуск
/EquinoxOS (Normal)
    protocol: limine
    path: boot():/sys/kernel.elf
    resolution: 1920x1080x32
    interface_resolution: 1920x1080
    module_path: boot():/res/font.psf

# Пункт 2: Запуск с отладочными логами в консоли ядра
/EquinoxOS (Debug Console)
    protocol: limine
    path: boot():/sys/kernel.elf
    cmdline: boot_debug=1
    resolution: 1920x1080x32
    interface_resolution: 1920x1080
    module_path: boot():/res/font.psf